### ISSUE TITLE
프로젝트 제안서 질문입니다.

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#1]
프로젝트 제안서의 동작예시를 보면
mapdata.txt가 아래와 같이 되어있습니다.

6
Denny's Bread / 0 6 13 0 0 1
Chodenny's Car shop / 0 0 5 6 0 5
Granddey's Go Kicking / 2 0 0 7 4 7
Labuajiea's Yoga class / 0 6 0 0 3 5
Grandy's Kicking Class / 0 0 5 2 0 9
Jeawon's Computer Academy / 5 6 8 4 5 0

여기서 PRINT명령어 등으로 출력하면 6X6의 행렬이 나와야 하는데 5X5로 나와있는 이유가 있나요?

**Comment by Lukious** [comment]
입력에 알맞게 PRINT기능에 충실하게 출력을 하도록 해주시면 됩니다.

제안서 동작예시 대로의 입력이라면 6x6의 행렬이 출력되는 것이 맞습니다.

해당 부분은 수정될 예정이나 이외의 기능에 대해서도 예시 출력 보다는 [**기능적 명시**]에 알맞게 출력 되도록 프로젝트를 진행해 주시면 됩니다.

예시 출력은 모두 **출력 포멧**에 관한 안내이며 프로젝트 문서에서 제안한 mapdata.txt 입력과는 상관 없습니다.

**Comment by rang21c** [comment]
넵 알겠습니다 감사합니다.
