### ISSUE TITLE
질문 두개 있습니다

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#10]
1. Vertex의 키에 대한 특별한 정보를 찾을 수 없었는데, 그냥 들어온 순서대로 키를 부여하고 이를 정렬하여 저장하면 되는지 알고 싶습니다. 만약 이래도 문제가 없다면, Vertex의 constructor 두 개중에서 사용하는 constructor만 구현하고 사용하지 않는 constructor는 에러를 던지도록 해도 괜찮은지 알고 싶습니다.
3. 고려하지 않아도 된다는 것이 프로그램을 채점할 때 절대 들어오는 입력이 아니라는 것을 확인하고 싶습니다.

**Comment by Lukious** [comment]
1. 네 들어온 순서대로 키를 부여하여 구현하셔도 상관없습니다.

2. 네 맞습니다.
