### ISSUE TITLE
구현해야 하는 항목들에 대해 질문 세 개 있습니다.

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#11]
1.
```
...사용법)CONFIG –-sort quick...
...‘—'를통해...
...있으며–sort의경우...
```
제안서 문서에서 CONFIG에 대한 설명을 보면 위와 같이 서로 다른 3개의 하이픈 (마이너스 기호, em dash, en dash)을 사용합니다. 사용법에서 CONFIG 바로 뒤어 오는 하이픈의 경우에는 2개의 서로 다른 하이픈이 붙어 있는데, 실제 사용법은
```
CONFIG -sort quick (한 개의 일반 마이너스 기호)
```
가 맞는지 알고 싶습니다.
2.
```
/// find the path from startVertexKey to endVertexKey with BFS (stack and queue)
	std::vector<int> FindPathDfs(int startVertexKey, int endVertexKey);
```
https://github.com/Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3/blob/cc5df9ac2dd2a404504fe08eb24df560618de794/Window/Graph.h#L51에 보면 BFS를 구현하라고 적혀있지만 함수명은 DFS이고, BFS에 대한 함수는 존재하지 않습니다. 실습 영상에서 보면 DFS를 설명하고 나중에 BFS를 설명하겠다고 하는데, PDF에 보면 BFS에 대한 내용만 있고 DFS는 언급이 없습니다. 무엇을 구현하는 것이 맞는지 알고 싶습니다.
3. 길을 탐색할 때 들어온 그래프가 connected 그래프가 아니라서 경로가 없는 경우는 고려하지 않아도 되는지 알고 싶습니다.

**Comment by Lukious** [comment]
1. 하이픈 하나가 맞습니다. 오타 수정하도록 하겠습니다.

2. BFS가 맞습니다. 코드는 수정할 예정이니 모든 스펙은 '제안서'를 따라주시면 되겠습니다. 
과제 출제자와 실습조교가 달라 의도치 않게 가끔 커뮤니케이션에 오류가 발생할 때가 있습니다. 😢
과제 채점은 100% '제안서'를 바탕으로 진행될 예정이니 **제안서만 확인**해서 구현해 주시면 되겠습니다.
(차후 채점에 대한 확인 방문시에도 '제안서'에 나온 내용대로 이의 신청을 받을 예정입니다.)

추가로 코드상에 문제에 대해서는 업데이트하도록 하겠습니다. 코드상의 문제를 찾아주어서 정말 감사합니다 🙇‍♂️

3. 네 해당사항은 고려 대상이 아닙니다.
INPUT Data는 상식적인 (구동가능한) 데이터가 입력될 예정임으로 너무 많은 예외 상황들을 생각하시지는 않아도 괜찮습니다! 🙂
(그럼에도 이러한 예외상황들에 대한 구현 및 처리를 진행해보고 고찰에 작성해 본다면 평가에 높은 점수를 받으실 수 있습니다)
