### ISSUE TITLE
컴파일링 할 때 파일 추가

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#12]
안녕하세요. 이번 과제에 보면 MinHeap의 경우에는 cpp 파일이 존재하지 않습니다. 선언과 구현을 분리해서 프로그램을 작성하고 싶다면 해당 파일을 임의로 생성해서 쓸 수 있나요?

**Comment by Lukious** [comment]
1. 자유롭게 생성하여 사용하셔도 상관 없습니다.
기능이 제안서와 동일하다면 구현의 method에 대해서는 자유롭게 접근하셔도 됩니다.
