### ISSUE TITLE
힙정렬 구현시 질문입니다.

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#13]
CONFIG를 이용해서 교체할 알고리즘중 하나인 힙정렬을 구현할 때 
다익스트라 알고리즘 구현시 사용한 MinHeap.h헤더파일을 사용하여 구현해도 무방한가요?
아니면 따로 구현해야하나요?
감사합니다

**Comment by Lukious** [comment]
해당 헤더파일을 사용하여 구현하여도 무방합니다
코드 재사용성이 높아짐으로 오히려 추천드리는 방법이며 해당 내용등을 고찰에 작성해 보아도 좋을것 같습니다^^
