### ISSUE TITLE
BFS와 DFS에 관한 질문

### ISSUE THREAD

**Issue by jungame3757** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#14]
이전에 올라온 이슈에서 BFS명령어밖에 없기에 BFS만 구현하면된다했는데, 이번 강의에 올라온 내용을보니 DFS로 구현하라는 내용이 있어 궁극적으로 둘다 구현하되 BFS만 명령어로 구현하라는 의미인지 궁금합니다.

**Comment by Lukious** [comment]
기존 ISSUE 내용 인용하도록 하겠습니다
https://github.com/Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3/issues/11

BFS가 맞습니다. 코드는 수정할 예정이니 모든 스펙은 '제안서'를 따라주시면 되겠습니다.
과제 출제자와 실습조교가 달라 의도치 않게 가끔 커뮤니케이션에 오류가 발생할 때가 있습니다. 😢
과제 채점은 100% '제안서'를 바탕으로 진행될 예정이니 제안서만 확인해서 구현해 주시면 되겠습니다.
(차후 채점에 대한 확인 방문시에도 '제안서'에 나온 내용대로 이의 신청을 받을 예정입니다.)
