### ISSUE TITLE
질문 2개 더 있습니다.

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#15]
1. err.txt와 관련 코드 (Manager의 ferr 등)는 제안서에 언급이 없으므로 이를 모두 삭제하고, 그냥 log.txt에 모든 값들을 출력하는 것이 맞는지 확인하고 싶습니다.
2. 지금까지 배운 내용에서 나온 BFS의 경우 weight를 고려하는지 않았는데, 이번 프로젝트에서도 weight와 무관하게 경로를 검색하나요, 아니면 queue에 현재 탐색중인 vertex에서 나오는 edge들을 weight가 증가하는 순서대로 넣어야 하나요?

**Comment by Lukious** [comment]
1. 네 맞습니다 log.txt 에 모든 값들을 출력해 주시면 됩니다.

2. 의도하였던 바는 Weight를 고려하여 진행해야하였지만 제안서 상에 해당 spec이 애매모호하게 간접적인 언급만 있었던 것을 확인 하였습니다. 혼란을 피하기 위해 Weight는 고려하지 않는 방면으로 제안서를 수정하도록 하겠습니다. 제안서상 문제일 수 있었던 부분을 잘 집어주어 감사합니다.😊
