### ISSUE TITLE
라빈카프 압축법칙 관련 추가질문입니다.

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#16]
#4 번 이슈 2번 질문에 이어서 질문드립니다.
Benney's Carshop Benney's Class이라는 문자열이 있을때 공백을 포함하여 비교를 진행하라고 하셨는데,
그럼 위의 문자열을 압축하게 되면 나오는 결과가 궁금합니다.
1. "Benney's C*Carshop Class"
2. "Benney's C*arshop Class"
3. "Benney's C*arshop lass"
4. "Benney's C*arshop Class"
            .
            .
            .
위의 결과 등에서  정답을 무엇으로 봐야 하나요?
이슈를 읽어보면 3번이 중복된경우가 없으니 정답인것같긴한데 헷갈려서 다시 질문드립니다
아니면 정답이 없고 그냥 어떻게든 줄이기만 하면 다 정답인지도 궁금합니다

**Comment by Lukious** [comment]
문자열 압축은 가장 긴 '문자열'에 대한 압축입니다. 가장긴 문자열은 'Benney's C'임으로 3번이 맞습니다.
