### ISSUE TITLE
BFS는 weight를 고려하지 않아도 되나요?

### ISSUE THREAD

**Issue by jungame3757** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#17]
BFS를 구현할 때 거리값은 고려하지 않고 최단경로를 구해도 되나요?

**Comment by Lukious** [comment]
당초 의도하였던 바는 Weight를 고려하여 진행해야하였지만 제안서 상에 해당 spec이 애매모호하게 간접적인 언급만 있었던 것을 확인 하였습니다. 혼란을 피하기 위해 Weight는 고려하지 않는 방면으로 제안서를 수정하도록 하겠습니다.

따라서 weight를 고려하지 않고 최단경로를 구해 주시면 되겠습니다.
