### ISSUE TITLE
Queue 구현방식

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#18]
Queue를 new로 생성한 배열로 데이터를 저장하고, 포인터를 앞으로 1씩 움직이면서 구현하는 방식이 필수인가요, 아니면 자기가 원하는 대로 구현할 수 있나요? (vector를 사용해서 구현)

**Comment by Lukious** [comment]
1. 원하시는대로 구현하셔도 됩니다. 특히 vector를 사용한 구현은 구현 방법이나 코드의 명료성이 더욱 높아지기 때문에 오히려 추천드리고 싶은 구현 방법입니다.

해당 내용같은 경우 고찰에 잘 풀이하여 적어 제출해 주시면 평가에 높은 점수로 반영될 수 있을 것 입니다.
