### ISSUE TITLE
chrono라이브러리 사용시 질문입니다.

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#19]
정렬 알고리즘을 chrono라이브러리를 이용해서 시간을 비교해보라고 하셨는데
과제제출시에 로그파일에 수행시간이 출력되도록 제출하나요
아니면 chrono라이브러리 관련 코드는 적어놓지만 로그파일에는 출력하지않고 제출하나요?

**Comment by Lukious** [comment]
1. 레포트 상에서 성능 비교를 위한 구간임으로 주석처리 해두시면 됩니다.
로그파일에는 별도로 출력할 필요 없습니다.
