### ISSUE TITLE
Floyd 알고리즘의 에러코드 관련 질문입니다.

### ISSUE THREAD

**Issue by rkdehdgns1230** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#20]
제안서 상에 BELLMANFORD를 수행할 때만 NegativeCycleDetected 에러를 return하도록 표기되어있는데, FLOYD의 경우에는 NegativeCycleDetected 에러코드를 return하지 않아도 되는 것인지 궁금합니다.
 또 그렇다면 FLOYD의 경우 음수 사이클의 형성에 대한 예외처리를 따로 하지 않아도 되는지 질문 드립니다.

**Comment by Lukious** [comment]
1. 에러코드는 제안서 문서에 따라서 출력진행해 주시면 됩니다. 음수 사이클에 대한 예외처리는 자체적으로 진행해 주시면 되겠습니다.

**Comment by rkdehdgns1230** [comment]
제안서 문서에는 Floyd에서 음수 사이클에 대한 에러코드를 따로 명시하지 않고 있는데, Floyd에서도 Bellmanford와 같이 음수 사이클이 발견된 경우 204(NagetiveCycleDetected)를 함수에서 return하도록 구현하면 될까요?

**Comment by Lukious** [comment]
네 그래주시면 됩니다!
