### ISSUE TITLE
weight를 고려하지 않는 BFS의 결과 관련 질문 드립니다.

### ISSUE THREAD

**Issue by HunSeongPark** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#21]
안녕하세요. 고생 많으십니다.

이번 BFS에서는 weight를 고려하지 않은 path를 출력하라고 하셨는데, 

그렇다면 다익스트라와 같은 shortest path 알고리즘과는 다른 path와 length가 나올 수도 있는건가요?

감사합니다.

**Comment by Lukious** [comment]
1. 같은 결과가 나오는 상황도 있겠지만 weight에 따라 다른 결과가 나오는 상황이 더 많을 것입니다. 기본적인 알고리즘 구조에서 고려하는 내용 자체가 다름으로 알고리즘을 잘 이해하시고 작성해 보시면 되겠습니다
