### ISSUE TITLE
라빈카프 압축 법칙에 관하여 질문드립니다.

### ISSUE THREAD

**Issue by bnk159hair** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#22]
안녕하세요 조교님 고생하십니다 

1. "Denny's Bread Jeawon's Computer Academy Labuajiea's Yoga class " 에서는 's가 가장 긴 문자열인데 해당 경우에는 Denny Bread Jeawon Computer Academy Labuajiea's *Yoga class 가 되는 것인가요? 아니면 해당 경우에는 압축을 시행하지 않는 것인가요? 만약 다른 경우로 압축이 시행된다면 어떠한 결과가 나오는지 궁금합니다.

2. 만약 압축 전 문자열이
Fenny's Bread Chodenny's Car shop Labuajiea's Yoga class 일때 
F Bread Chodenny's* Car shop Labuajiea's Yoga class 로 압축시키는 것이 맞는지 아니면 다른 경우로 시행되는지 궁금합니다.

3. RabinKarpCompare에서 인자로 받는 변수의 타입이 const char *인데 string으로 변경해도 되나요?

**Comment by Lukious** [comment]
1. 's와 다음칸의 공백을 포함하여 ['s ]가 가장긴 문자열이 됩니다. 해당 문자열을 가장 긴 문자열로서 압축을 시행해 주시면 됩니다 .

2. 마찬가지로 공백까지 압축되어야 합니다. 이외에는 정답입니다.

3. 네 상관없습니다. 자유롭게 수정하셔서 진행하셔도 됩니다.
