### ISSUE TITLE
bfs 구현관련하여 질문드립니다.

### ISSUE THREAD

**Issue by bnk159hair** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#23]
제안서 상에는 bfs를 통한 경로를 구하라고 되어있고 올라온 질문에서는 최소경로를 구하라 하셨습니다
제공된 데이터를 기준으로 0, 3을 bfs를 통해 찾게 된다면 
순회 결과 값인 0, 1, 2, 5, 3이 맞나요? 아니면 최소 경로인 0, 1, 3이 맞나요?

**Comment by Lukious** [comment]
BFS와 같은 경우는 사전에 안내가 부족했기 때문에 순회 탐색 구현 결과 혹은 최소 경로 탐색 구현 결과 모두 정답 처리를 진행하도록 하겠습니다. 이미 구현하신 내용이 있다면 해당 내용을 바탕으로 구현을 진행해 주시면 되겠습니다.
