### ISSUE TITLE
큐 구현시 사이즈 질문드립니다

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#24]
큐 구현시 배열을 동적할당하여 구현하였는데
채점시에 사용하는 데이터가 얼마나 되는지 궁금합니다.
큐 사이즈 200정도면 무리없이 동작하나요?

**Comment by Lukious** [comment]
희소 그래프에 대한 탐색을 진행할 예정이기 때문에 큐 사이즈 200개 정도라면 전혀 문제 없이 동작가능합니다. 

추천드리는 사이즈는 100 가량입니다.
