### ISSUE TITLE
라빈카프 공국 규칙 질문입니다.

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#25]
![image](https://user-images.githubusercontent.com/33370179/100705787-2d94f500-33eb-11eb-8722-c2b78db77139.png)

3번 규칙에 보면 "2의 규칙이 적용된 이후에"라고 나와있으니 2의 규칙에서 간선의 비용이 감소되지 않았으면 3번을 아예 적용시키지 않아도 되는것이 맞나요?
아니면 2에의해 감소되지 않아도 3번을 적용해야 하나요?

항상 고생하십니다

**Comment by Lukious** [comment]
1. 순서를 명확하게 하기 위해서 서술한 것이며 비용이 감소 되지 않았다 하더라도 3의 규칙이 적용되어야 합니다. 

간선의 비용이 소수점 올림 등으로 인해서 감소되지 않았다 하더라도 '규칙이 적용된'이라는 용어는 유지됨으로 3은 그대로 적용되어야합니다.

**Comment by bnk159hair** [comment]
조교님 그러면 3번 규칙은 2번 규칙이 적용되면 무조건 적용되는게 맞죠?
2번 규칙이 적용이 안됬으면 3번은 적용이 안되는것이고
2번 규칙이 적용되었다면 간선 비용의 감소되는거에 상관없이 3번이 무조건 적용이구요
