### ISSUE TITLE
조교님 25번 질문 관해 추가 질문 드립니다

### ISSUE THREAD

**Issue by bnk159hair** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#26]
조교님 그러면 3번 규칙은 2번 규칙이 적용되면 무조건 적용되는게 맞죠?
2번 규칙이 적용이 안됬으면 3번은 적용이 안되는것이고
2번 규칙이 적용되었다면 간선 비용의 감소되는거에 상관없이 3번이 무조건 적용이구요

**Comment by Lukious** [comment]
아닙니다 2번 규칙의 적용과는 상관없이 무조건 3번 규칙이 적용되어야 합니다.

적용이라는 단어를 파라미터의 값 변환으로 해석하지 마시고 process를 거치는 모든 상황(알고리즘의 적용을 통해서 값이 변하지 않았다 하더라도 알고리즘 process는 거친것 임으로)을 적용으로 이해해 주시면 됩니다.

즉 어떤 상황에서도 1,2,3,4 규칙은 적용되어야(값은 변하지 않더라도 처리는 거쳐야) 합니다.
