### ISSUE TITLE
라빈카프 공국 규칙에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by hnym1104** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#27]
![image](https://user-images.githubusercontent.com/61773345/100720499-69d35000-3401-11eb-9419-f6d4f96aefd2.png)
위의 1번 규칙에서 주인 이름이 5글자 이상 같을 경우 간선비용을 10% 낮추는 작업을 한번만 수행하면 되나요?
예를 들어 주인의 이름이 5글자, 6글자, 7글자 동일할 경우에 모두 해당될 경우 10% 낮추는 작업을 한번만 수행하면 되는지 3번을 수행해야 하는지 질문 드립니다.
감사합니다.

**Comment by Lukious** [comment]
1번만 수행하면 됩니다!
