### ISSUE TITLE
라빈카프 압축 질문 있습니다

### ISSUE THREAD

**Issue by bnk159hair** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#28]
pdf 설명에서 

2. 주어진 문자열에 대하여, 두 번 이상 등장한 부분 문자열 중 가장 길이가 긴
문자열은 해당 단어 뒤에 ‘*’를 붙임으로서 압축 할 수 있다. (길이가 동일 할
경우 모든 단어에 대해서 압축 할 수 있다, 공백 또한 함께 압축한다.) 

라고 되어있습니다. 
그렇다면 가장 긴 문자열의 길이가 3이라 할때 길이가 3인 문자열이 두 개 혹은 그 이상 있을때 
모든 단어를 압축해야한다는 것인가요?
그중 한 단어만 압축하는 방식은 불가한가요?

**Comment by Lukious** [comment]
네 모든 단어를 한번에 압축해야 합니다.
