### ISSUE TITLE
Floyd 알고리즘 음수 사이클 에러 처리 관련 질문 드립니다.

### ISSUE THREAD

**Issue by HunSeongPark** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#29]
안녕하세요. 고생 많으십니다.

다름이 아니라 floyd 의 에러 처리 중 제안서 처음 부분에는 음수 사이클 발생 시 에러 처리를 하라고 되어 있는데,

제안서 아래 세부 Error code 처리 부분에는 Floyd는 음수 사이클 발생 시 에러 처리에 대한 부분이 없습니다.

제안서에 따른 error code 처리와 같이 floyd의 경우 음수 사이클에 대한 error 처리 없이 진행하면 되는 것인 지 궁금합니다. 

감사합니다.

**Comment by Lukious** [comment]
https://github.com/Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3/issues/20

기존 이슈임으로 해당 이슈 링크하도록 하겠습니다.
