### ISSUE TITLE
28번 질문 관련하여 다시 한번 질문드립니다.

### ISSUE THREAD

**Issue by bnk159hair** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#30]
제 질문 의도가 혹시 모호하게 전달된것이 있나 싶어 질문드립니다.
조교님께서 모든 단어를 압축해야 한다는 의도가
Denny's Bread 와 Labuajiea's Yoga class의 경우에는 "'s "가 가장 긴 문자열인데 모든 문자열에 있어 "'s "를 압축하는것을 말씀하는 것인지, 
아니면 Clany's Bread 와 Labuajiea's Yoga class 의 경우에는 "cla" 와  "'s " 가 문자열의 길이가 3인데 cla와 's 를 각각 모두 압축시켜야 한다는 것인지 궁금합니다

**Comment by Lukious** [comment]
질문이 모호하게 작성되어 이해가 어렵지만 가장 긴 문자열이 같은 길이로 여러개가 나올 때에 대한 질문 인것 같아 해당 내용으로 답해드립니다.

가장긴 문자열이 두개일경우 두개를 각각 압축해 주시면 됩니다.

하지만 우선 테스트 입력의 경우 가장긴 문자열이 한번만 나타나도록 입력할 예정이니 평가 점수에 있어서 고려하실 필요는 없을 것 같습니다.

마감이 얼마 남지 않았으니 효율적인 시간 분배로 작업해 보시면 좋을것 같습니다.
