### ISSUE TITLE
질문 네 개 있습니다.

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#31]
1. 제안서에 보면 NegativeCycleDetected가 BellmanFord에만 적용하도록 되어 있습니다. Floyd에 대해서는 negative cycle 감지를 하지 않아도 되는 것인가요?
2. Update에서 그래프 업데이트가 실패하는 경우가 무엇인지 알고 싶습니다. 그래프가 존재하지 않는 경우 외에는 명시된 예외 상황이 없어서 딱히 없을 것 같은데, 어떤 경우에 이 값을 출력해야 되나요? 
3. Algorithm에서 각 명령어에 대해서도 작성해야 하는지, 아니면 각 명령어의 주요가 되는 부분만 (UPDATE에서 실제로 단어 비교하는 부분에 대해서만 설명, Dijkstra만 설명하고 Dijkstramin에 대한 설명은 중복되므로 제외하는 등) 설명하는 되는지 알고 싶습니다.
4. 저번 대면 강의에서 각 객체 사이에서의 연관성을 표현하는 다이어그램과 같이 추가로 이번 보고서에 작성해야 하는 내용을 나열했었는데, 이것에 대한 정보를 어디서 찾을 수 있는지 알고 싶습니다.

**Comment by Lukious** [comment]
1. 마찬가지로 에러 코드에 대한 내용임으로 이전의 이슈를 인용하면, 모든 구현은 기능적인 단위로 평가할 예정이니 음수 사이클 검사를 반영하게 되는 에러코드에 스펙을 참고하여 작업해 주시면 됩니다.

2. 특정한 case에 대한 내용이라기 보다는 try catch등의 디버깅 코드를 얼마나 코드에 활용 할 줄 아느냐가 목표인 부분이였기 때문에 입력 자체가 잘못 되거나 하는등 모든 발생가능한 에러들에 대해 출력해 주시면 됩니다. (하지만 꼭 try catch를 사용하실 필요는 없습니다 if문등으로 가볍게 구현 하셔도 무방합니다.)

3. 모든 각 명령어에 대해서 작성해야 합니다. 다만 중요하지 않은 명령어에 대하여 분량에 대해서는 여유를 두고 채점하도록 하겠습니다.

4. 해당 부분은 git commit log에 보면 initial upload보고서에서 확인 하실 수 있습니다. 하지만 전반적으로 프로젝트 구현에 시간이 많이 걸리게 될 것 같아 이번 프로젝트에 다시 제외한 부분임으로 굳이 작성하실 필요는 없으나 작성시 보고서의 내용이 상당히 강화된 것임으로 높은 보고서 점수 항목으로 반영도록 하겠습니다.
