### ISSUE TITLE
압축에 대한 질문입니다.

### ISSUE THREAD

**Issue by kimteak** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#32]
별을 입력하면 사라져서 별 대신 !으로 추가했습니다.

1.(#30번 질문과 같은 내용인 것 같습니다.)
압축 법칙 2에서 길이가 동일할 경우 모든 단어에 대해서 압축 할 수 있다. 가 의미가 궁금합니다.
Denny's ToyStore denn's ktoys라는 문자열을 압축할 때 denn과 toys가 문자열 길이 4로 동일하게 2번 등장할 때. denn과 toys를 전부 압축해 denn!y's ToyS!tore 's k가 맞나요?
아니면 한가지 문자만 압축하는 것인가요?

2.
1번에서 2문자를 다 압축하는 것이라면
Dennnny's Toy denn's Nnnn라는 문자열을 압축할 때 denn과 nnnn이 문자열 길이 4로 동일하게 2번 등장하는데 먼저 압축 돼  !가 생겨 nnnn은 압축하지 않는
Denn!nny's Toy 's Nnnn이 맞나요? 
아니면 !는 무시하고 전부 압축하는
Denn!nn!y's Toy 's 가 맞나요?

3.
문자열 2개를 연결할 때 이어주는 공백을 추가해야 하나요?
a's toy와 b's toy를 이어줄 때  a's toy b's toy 와 같이 이어 줘야하나요?
아니면 mapdata에서 간판명을 받을 때 /를 기준으로 이전까지 구분해 a's toy(공백) 처럼 공백까지 있게 구분되어 연결할 때 a's toy b's toy 으로 형성되는 것인가요?

**Comment by Lukious** [comment]
1. 30번 질문에 답하였습니다 확인 부탁드립니다!

2. 한 항목은 처리 과정을 동시에 거친다고 생각해 주시면 됩니다. 따라서 Denn!nny's Toy 's Nnnn 가 맞습니다.
    하지만 위에서 말씀 드렸듯이 테스트 케이스는 중복되는 가장 긴 문자열의 중복이 없을 예정임으로 시간을 잘 분배하여 구현해 주시면 되겠습니다.

3. 연결 방식은 크게 제한하지 않겠습니다. 공백을 추가하셔도 안하셔도 상관 없지만 개인적으로는 추가하지 않는것을 추천드립니다.
