### ISSUE TITLE
문자열 압축시 경로선택 질문입니다

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#33]
문자열 압축시에
최단경로     : 0 5 3
정렬된경로 : 0 3 5
라고 가정했을때

0 5 3과 0 3 5 둘중에 어떤 가게 이름의 조합으로 압축하면 되나요?
"최단 경로를 찾고 난 후의 최종 출력물" 이라고 되어있는데 좀 모호해서 질문드립니다

**Comment by Lukious** [comment]
최종 출력물 임으로 정렬된 경로(0 3 5)에 대하여 압축하면 됩니다.
