### ISSUE TITLE
라빈카프 압축에 대해 질문드립니다.

### ISSUE THREAD

**Issue by KIMMINTAE98** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#34]
![image](https://user-images.githubusercontent.com/26856370/100849977-7a013300-34c6-11eb-9037-87363f0e4f6f.png)

위 2, 3번 규칙에 대해
1. 문자열 압축이 중복된 가장 긴 부분 문자열에 대해서만 진행되고 끝나는지 아니면
2. 가장 긴 문자열을 압축하고 Shop, Class, Academy에 대해서만 추가적으로 압축해야하는지 질문드립니다.
2로 이해했을 경우,
denny's bread shop chodenny's car shop labuajiea's yoga class 에 2번 규칙이 적용되어 [denny's ]을 압축
-> denny's *bread shop chocar shop labuajiea's yoga class 
denny's *bread shop chocar shop labuajiea's yoga class 에 3번 규칙이 적용되어 [Shop]을 압축
-> denny's *bread shop chocar  labuajiea's yoga class 
가 최종 압축 결과가 되는건가요?

**Comment by Lukious** [comment]
네 맞습니다. 스펙대로 2번의 처리이후 제시한 단어와 같은 출력이 있다면 3번의 처리 진행해 주시면 됩니다
