### ISSUE TITLE
#31에 이어 추가 질문입니다.

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#35]
제안서에 보면 "BFS, Dijkstra, Bellman-Ford, Floyd, 라빈-카프 알고리즘에 대하여 각각 예시를 들어 설명할 것"라는 내용이 있는데, #31에서 보고서의 Algorithm 에는 모든 명령어 (LOAD, PRINT 등등)에 대해서 pseudo code를 작성하라고 하셨습니다. 보고서의 algorithm을 작성할 때 명령어에 대해서도 예시를 써야 하나요?

**Comment by Lukious** [comment]
네 프로젝트를 진행하면서 사용해 보셨을 간단한 예시를 통해서 설명해 주시면 됩니다. 

내용만 있으면 괜찮은 부분이니 자유롭게 작성해 주시면 됩니다.
