### ISSUE TITLE
간선 비용 줄이는 방법

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#36]
간선 비용이 음수일 때 Update로 값을 줄이면 무조건 감소, 즉 절댓값이 증가하도록 설계하는 것이 맞는지 확인하고 싶습니다.
-10 -> 10퍼센트 감소 -> -11

**Comment by Lukious** [comment]
해당 부분은 정확히 서술된바 없으니 절대값의 감소, 혹은 음수로의 감소 모두 허용하도록 하겠습니다. 

즉 둘 다 맞는 구현으로 하겠습니다.
