### ISSUE TITLE
BFS 경로 거리 관련 질문입니다.

### ISSUE THREAD

**Issue by doomdabo** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#37]
앞서 BFS에 관해 답해주셨는데, 순회 또는 최단 경로 둘 다 구현 가능하다고 하셨습니다.

주어진 예시에서 0 3 인 경우에, 순회 탐색으로 한다면, 0 1 2 5 3이 됩니다. 이 때 경로 weight들을 더하는 path length는 어느 기준으로 해야하는 것인가요?

순회 탐색에 따라 0->1->2->5, 1->3의 weight를 더해도 괜찮은 것인가요?

감사합니다.

**Comment by Lukious** [comment]
네 제안하신 방법대로 더하여 구하여도 무방합니다.
