### ISSUE TITLE
컴파일 관련 감점

### ISSUE THREAD

**Issue by MangoCubes** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#38]
컴파일이 너무 오래 걸리는 경우, 그리고 컴파일이 다른 버전으로만 될 때 얼마나 감점되나요?

**Comment by Lukious** [comment]
컴파일 시간은 상관없으며, 컴파일 버전이 다른 경우 리눅스환겅 컴파일 실패로 간주됩니다.

컴파일 실패시 우선 코드부분 0점처리 되며  일부환경 빌드(윈도우에서만 빌드)와 동일하게 이후 방문하여 자신의 PC환경에서  제출한 코드가 구동되는 것을 보여주실 경우 전체  받게되는 코드 점수의 50%를 인정해드립니다.

즉,  코드 점수가 80점일 경우 40점만 10점일 경우 50점만 인정 받게됩니다.
