### ISSUE TITLE
라빈카프 압축 법칙 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by LimYooyeol** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#4]
1. 라빈카프 압축 법칙에서 압축의 정확한 의미가 궁금합니다. 두 번 이상 등장하고 그 중 가장 길이가 긴 부분 문자열은 한 단어만 남겨두고 그 뒤에 '*'을 추가하는게 맞나요?

 2. 부분 문자열은 스페이스(' ')를 포함하지 않고 단어단위에서 확인하는게 맞는지 궁금합니다. 예를 들어 Benney's Carshop Benney's Class 라는 문자열이 있다고 했을 때, 두 번 이상 등장한 가장 긴 부분 문자열을 "Benney's C"로 보는게 맞는지 "Benney's"로 보는게 맞는지 알고싶습니다.

 3. Result Manager::RabinKarpCompare(const char* Comparestring) 함수의 쓰임과 반환형이 Result인 이유가 궁금합니다.

**Comment by Lukious** [comment]
1. 네 맞습니다 전반적으로 문자열의 길이를 줄이는데 초점을 맞춰서 스펙문서 그대로 작업 진행해 주시면 됩니다.

2. 스페이스를 포함해서 비교하여야 합니다. 예시의 경우 Benney's C로 보는것이 타당합니다.

3. 라빈카프 비교를 진행하는 함수입니다. 반환형의 경우 스켈레톤 코드였기 때문에 직관적인 이해를 위헤 Result structure를 가정하여 제안한것입니다. 수업시간에 전해드렸듯 flag형식으로 비교를 진행하셔도 되고 string을 반환하는 타입으로 설계하셔도 됩니다.

**Comment by LimYooyeol** [comment]
1번 질문에 대해서 추가적으로 궁금한 부분이 있습니다. 
문서에서 Benney's Carshop Benney's Oakshop 은 앞에 있는 Benney's 를 남겨두고 Benney's* Carshop Oakshop으로 압축되지만 
Denney's Bread Chodenny's Car shop Labuajiea's Yoga class-> Bread Chodenny's* Car shop Labuajiea's Yoga class로 압축되는 것처럼 압축 시 남게되는 단어의 기준이 궁금합니다.
문자열의 길이를 줄이는 것에 초점을 두고 남는 단어의 위치는 상관없는건가요?

답변 감사드립니다.

**Comment by Lukious** [comment]
문자열의 길이를 줄이는 것에 초점을 두면 될 것 같습니다.

중복된 부분에 대하여 앞부분이 남던지 뒷 부분이 남던지 문자열에서 중복된 곳이 한번만 있으면 상관 없습니다. (그럼으로 인해서 문장이 변형되어 이해가 되지 않아도 상관이 없습니다.)

채점 자체를 중복된 부분이 있는지 없는지를 통해서만 채점을 진행할 예정임으로 이를 고려하여 프로젝트를 작성하시면 됩니다.
