### ISSUE TITLE
stack관련 질문입니다.

### ISSUE THREAD

**Issue by doomdabo** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#5]
안녕하세요.
헤더파일 중 Stack.h가 있는데 이 헤더파일은 언제 쓰이나요? 
만약 BFS를 큐를 활용해 구현하고자 하면 Stack을 따로 구현하지 않아도 되나요?

또한 BFS를 구현할 때 큐를 직접 구현해서 사용한다고 나와있습니다.
그러나 주어진 스켈레톤 코드에는 큐와 관련된 헤더 파일이 따로 없습니다.
큐의 헤더파일은 새로 생성해서 사용해도 문제되지 않나요?
감사합니다.

**Comment by Lukious** [comment]
stack을 스택을 활용하여 구현 하였을때 사용하는 헤더파일 입니다.
큐를 활용해 구현하고자 한다면 관련 파일을 사용하실 필요가 없습니다. 

구현방식은 큐를 활용하여 구현하는 방법을 추천하나 stack이나 재귀방식을 통해 구현하는 것 또한 인정한다. 이럴 경우 큐를 직접 구현하지 않아도 상관없으며 **기능이 동일하다면 배점도 동일하다.**

큐의 해더파일은 새로 생성해서 사용하면 됩니다.
