### ISSUE TITLE
Manager.cpp member 관련 질문입니다.

### ISSUE THREAD

**Issue by rkdehdgns1230** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#6]
안녕하세요 다름이 아니라 프로젝트를 진행함에 있어서  Manager.cpp 파일에 대해 궁금한 점이 몇가지 있어 질문 드립니다.

1. 프로젝트 제안서를 보게되면 error code와 결과 모두 log.txt에 출력하도록 되어있는데, 그렇게 되면 ferr 인자는 어떤 파일을 열기 위해 사용해야 하는 것인지 궁금합니다. 아니면 삭제해도 되는 member인지 궁금합니다.

2. 라빈카프 알고리즘을 이용해 문자열을 비교하기 위해서는 RabinKarpCompare 함수에 인자가 두 개 필요하다고 생각하는데, const char* CompareString 하나만을 인자로 받아 비교 연산을 수행하도록 스켈레톤 코드에 작성되어 있습니다. 왜 그런 것인지 궁금합니다.

3. 앞선 질문에서 DFS가 아니라 BFS를 구현하라는 점은 확인을 했습니다. 그러면 스켈레톤 코드로 제공되는 Stack.h이 아닌 Queue.h를 추가로 구현해서 BFS 방식 탐색을 구현하는 것이 맞는지 궁금합니다. 추가로 맞다면 Stack.h는 구현에 필요없는 헤더파일인지도 궁금합니다.

**Comment by Lukious** [comment]
1. 리눅스환경에서 디버깅시에 사용하시면 편하게 진행할 수 있을것 입니다. 구현하는데 문제가 없다면 (기능적으로 동일하다면) 삭제하셔도 무방합나다.

2. 해당부분은 의도했던 바와 다르게 이해하는 학생이 많아 금일 중에 수정될 예정입니다.

3. 이전 이슈에 올라왔던 내용임으로 해당 내용을 전달해드립니다.

stack을 스택을 활용하여 구현 하였을때 사용하는 헤더파일 입니다.
큐를 활용해 구현하고자 한다면 관련 파일을 사용하실 필요가 없습니다.

구현방식은 큐를 활용하여 구현하는 방법을 추천하나 stack이나 재귀방식을 통해 구현하는 것 또한 인정한다. 이럴 경우 큐를 직접 구현하지 않아도 상관없으며 기능이 동일하다면 배점도 동일하다.

큐의 헤더파일은 새로 생성해서 사용하면 됩니다.
