### ISSUE TITLE
명령어 인자 관련 질문 드립니다.

### ISSUE THREAD

**Issue by hnym1104** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#7]
프로젝트 문서의 Error Code 부분에서 BFS, DUKSTRA, DUKSTRAMIN, BELLMANFORD  명령어에는 명령어 인자가 부족한 경우에 대한 에러 명이 제시되어 있습니다. 이 명령어들을 제외한 LOAD, UPDATE, PRINT 등 다른 명령어들에 대해서는 명령어 인자에 관한 에러 명이 제시되어 있지 않아 질문드립니다. 이 명령어들에 대한 인자 예외 처리(ex. 명령어에 불필요한 인자가 존재할 때)는 고려하지 않아도 되는것인가요?

**Comment by Lukious** [comment]
네 제안서 위주로 구현해 주시면 되며 에러코드가 별도로 명시되어 있지 않은경우 별도로 추가 처리하셔야 할 에러 처리는 없습니다.

**Comment by MangoCubes** [comment]
그러면 mapdata에 있는 데이터가 제안서에 나온 형식과 다르거나, 뒤 weight matrix에 숫자가 부족하거나 너무 많은 일은 고려하지 않아도 된다는 것인가요?
