### ISSUE TITLE
라빈카프 공국 규칙 관련 질문드립니다.

### ISSUE THREAD

**Issue by jeongchanYu** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#8]
readme의 라빈카프 공국 규칙(대소문자는 무시한다) 항목 아래에

이후 변경된 Graph의 정보를 입력 텍스트 파일과 같이 출력한다. (초기 1회)

라고 명시되어 있습니다. 해당 기능은 UPDATE 명령에 구현하여야 하는것인가요? 실행 예시에 나와있지 않아 어떤식으로 나타내어야 할지 모르겠습니다.

혹은 PRINT -> UPDATE -> PRINT 로 UPDATE 전과 후에 PRINT를 통해 Graph 정보를 나타내면 되는것인가요?

**Comment by Lukious** [comment]
해당 부분 제안서 상의 오류로 확인되어 업데이트 하였습니다.

~이후 변경된 Graph의 정보를 입력 텍스트 파일과 같이 출력한다. (초기 1회)~  **삭제**

UPDATE command는 성공 여부만을 출력 하며 별도로 업데이트된 그래프정보를 출력 할 필요는 없도록 수정하였습니다.
그래프의 업데이트 확인은 별도로 PRINT명령어를 사용한 출력을 통해 확인하게 됩니다.

제안서 상의 오류를 찾아주셔서 정말 감사합니다. 🙇‍♂️
