### ISSUE TITLE
BFS 에러코드 & 정렬알고리즘관련 질문드립니다.

### ISSUE THREAD

**Issue by rang21c** [Lukious/2020_Kwangwoon_Univ_CE_DS_Project_3#9]
1.
제안서 7페이지에 BFS의 설명을 보면
"또는 음수인 Weight가 있는 경우 로그 파일(log.txt)에 알맞은 오류 코드를 저장한다." 라고 되어있고

제안서 10페이지 에러코드 203부분을 보면 BFS가 없는데 
BFS의 경우에는 음수인 Weight가 있는 경우 로그 파일에 저장을 해줘야하나요 아니면 무시하면 될까요?

2.
CONFIG명령어를 이용해서 정렬알고리즘을 선택 안해줬을 경우의
정렬 알고리즘 기본값은 원하는 알고리즘으로 설정하면 되나요?

**Comment by Lukious** [comment]
1. 에러코드 스펙에 명시가 되어 있지 않은 경우 구현하지 않으셔도 무방합니다.

2. 디폴트 알고리즘 하나를 설정해 두시면 됩니다. 평가시에는 CONFIG이후  다음 명령어들이 수행되게 됨으로 디폴트 정렬 알고리즘은 아무 알고리즘으로 설정해두시면 됩니다.
